version: '3'

services:
  doublecolorball-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    restart: always
    # 如果需要存储数据或配置文件，可以添加卷
    # volumes:
    #   - ./data:/app/data